// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.gold.protocol



sealed trait ResultCode extends com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = ResultCode
  def isSuccess: Boolean = false
  def isInternalServerError: Boolean = false
  def isRequestResourceNotFound: Boolean = false
  def isMethodNotAllow: Boolean = false
  def isMessageTypeError: Boolean = false
  def isInvalidMessage: Boolean = false
  def isUnrecognized: Boolean = false
  def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[ResultCode] = ResultCode
}

object ResultCode extends com.trueaccord.scalapb.GeneratedEnumCompanion[ResultCode] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[ResultCode] = this
  @SerialVersionUID(0L)
  case object SUCCESS extends ResultCode {
    val value = 0
    val index = 0
    val name = "SUCCESS"
    override def isSuccess: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INTERNAL_SERVER_ERROR extends ResultCode {
    val value = 10000
    val index = 1
    val name = "INTERNAL_SERVER_ERROR"
    override def isInternalServerError: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object REQUEST_RESOURCE_NOT_FOUND extends ResultCode {
    val value = 10001
    val index = 2
    val name = "REQUEST_RESOURCE_NOT_FOUND"
    override def isRequestResourceNotFound: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object METHOD_NOT_ALLOW extends ResultCode {
    val value = 10002
    val index = 3
    val name = "METHOD_NOT_ALLOW"
    override def isMethodNotAllow: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object MESSAGE_TYPE_ERROR extends ResultCode {
    val value = 10003
    val index = 4
    val name = "MESSAGE_TYPE_ERROR"
    override def isMessageTypeError: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INVALID_MESSAGE extends ResultCode {
    val value = 10004
    val index = 5
    val name = "INVALID_MESSAGE"
    override def isInvalidMessage: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends ResultCode {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
  
  lazy val values = Seq(SUCCESS, INTERNAL_SERVER_ERROR, REQUEST_RESOURCE_NOT_FOUND, METHOD_NOT_ALLOW, MESSAGE_TYPE_ERROR, INVALID_MESSAGE)
  def fromValue(value: Int): ResultCode = value match {
    case 0 => SUCCESS
    case 10000 => INTERNAL_SERVER_ERROR
    case 10001 => REQUEST_RESOURCE_NOT_FOUND
    case 10002 => METHOD_NOT_ALLOW
    case 10003 => MESSAGE_TYPE_ERROR
    case 10004 => INVALID_MESSAGE
    case __other => Unrecognized(__other)
  }
  def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = ProtocolProto.descriptor.getEnumTypes.get(2)
}